[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jzfmm"
version = "1.0.1"
description = "GPU-native fast multipole method and differentiable N-body simulations in JAX"
readme = "README.md"
authors = [{ name = "Jens Stücker", email = "jens.stuecker@univie.ac.at" }]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11"
dependencies = [
    "jztree>=1.1.0",
    "jax>=0.8.0",
    "numpy>=2.2.6",
]

[project.urls]
Homepage = "https://jstuecker.github.io/jzfmm/"
Repository = "https://github.com/jstuecker/jzfmm"
Issues = "https://github.com/jstuecker/jzfmm/issues"

[project.optional-dependencies]
cuda12 = ["jzfmm-cu12==1.0.1"]
cuda13 = ["jzfmm-cu13==1.0.1"]

[tool.setuptools]
package-dir = {"" = "../../src"}

[tool.setuptools.packages.find]
where = ["../../src"]
include = ["jzfmm", "jzfmm.*", "jzfmm_utils", "jzfmm_utils.*"]
