#!/usr/bin/env python3
"""Generate explicitly scheduled 3D CUDA M2L translators."""

from __future__ import annotations

from math import factorial
from pathlib import Path


HERE = Path(__file__).resolve().parent
ORDERS = (5, 6)


def indices_upto(p: int):
    for degree in range(p + 1):
        for z in range(degree + 1):
            for y in range(degree - z + 1):
                yield degree - y - z, y, z


def indices_fixed_reverse(degree: int):
    for z in range(degree, -1, -1):
        for y in range(degree - z, -1, -1):
            yield degree - y - z, y, z


def ncomb(p: int) -> int:
    return (p + 1) * (p + 2) * (p + 3) // 6


def scalar_literal(value: float) -> str:
    if value.is_integer():
        literal = f"{value:.1f}"
    else:
        literal = f"{value:.17g}"
    return f"tvec({literal})"


def recurrence(lines: list[str], p: int, flat: dict[tuple[int, int, int], int]) -> None:
    declared = {0}
    lines.append(f"        tvec d0 = G[{p}];")
    for q in range(p - 1, -1, -1):
        max_degree = p - q
        iflat = ncomb(max_degree) - 1
        for degree in range(max_degree, 0, -1):
            for index in indices_fixed_reverse(degree):
                axis = 2 if index[2] else (1 if index[1] else 0)
                count = index[axis]
                previous = list(index)
                previous[axis] -= 1
                previous2 = list(index)
                previous2[axis] -= 2
                previous_flat = flat[tuple(previous)]
                previous2_flat = flat.get(tuple(previous2), 0)
                rhs = f"dx[{axis}] * d{previous_flat}"
                if count > 1:
                    rhs += f" + {scalar_literal(float(count - 1))} * d{previous2_flat}"
                prefix = "tvec " if iflat not in declared else ""
                lines.append(f"        {prefix}d{iflat} = {rhs};")
                declared.add(iflat)
                iflat -= 1
        lines.append(f"        d0 = G[{q}];")


def contraction(
    lines: list[str],
    p: int,
    indices: tuple[tuple[int, int, int], ...],
    flat: dict[tuple[int, int, int], int],
) -> None:
    for kflat, k in enumerate(indices):
        kdegree = sum(k)
        lines.append("        {")
        lines.append(f"            tvec Lnew = {scalar_literal(0.0)};")
        for nflat, n in enumerate(indices):
            if kdegree + sum(n) > p:
                continue
            derivative = tuple(k[axis] + n[axis] for axis in range(3))
            dflat = flat[derivative]
            nfac = factorial(n[0]) * factorial(n[1]) * factorial(n[2])
            term = f"d{dflat} * Mp[{nflat}]"
            if nfac != 1:
                term += f" * {scalar_literal(1.0 / nfac)}"
            lines.append(f"            Lnew += {term};")
        kfac = factorial(k[0]) * factorial(k[1]) * factorial(k[2])
        scale = (-1.0 if kdegree % 2 else 1.0) / kfac
        if scale == 1.0:
            lines.append(f"            loc[{kflat}] += Lnew;")
        elif scale == -1.0:
            lines.append(f"            loc[{kflat}] -= Lnew;")
        else:
            lines.append(f"            loc[{kflat}] += Lnew * {scalar_literal(scale)};")
        lines.append("        }")


def generate(p: int) -> str:
    indices = tuple(indices_upto(p))
    flat = {index: iflat for iflat, index in enumerate(indices)}
    ncoeff = ncomb(p)
    lines = [
        "template<typename tvec>",
        f"struct GeneratedM2L<{p},0,3,tvec> {{",
        "    static constexpr bool available = true;",
        "",
        "    __device__ __forceinline__ static void apply(",
        "        const Vec<3,tvec>& dx,",
        f"        const Vec<{ncoeff},tvec>& Mp,",
        f"        Vec<{ncoeff},tvec>& loc,",
        "        int radial_kernel_kind,",
        "        const tvec* radial_kernel_params",
        "    ) {",
        f"        Vec<{p + 1},tvec> G;",
        f"        evaluate_radial_kernel_derivatives<{p},tvec>(",
        "            radial_kernel_kind, dx.norm2(), radial_kernel_params, G",
        "        );",
    ]
    recurrence(lines, p, flat)
    lines.append("")
    contraction(lines, p, indices, flat)
    lines.extend(["    }", "};", ""])
    return "\n".join(lines)


def main() -> None:
    output = HERE / "generated" / "m2l_specializations.cuh"
    sections = [
        "// Generated by src/fmdj_cuda/generate_m2l.py. Do not edit manually.",
        "#ifndef GENERATED_M2L_SPECIALIZATIONS_CUH",
        "#define GENERATED_M2L_SPECIALIZATIONS_CUH",
        "",
        *(generate(p) for p in ORDERS),
        "#endif // GENERATED_M2L_SPECIALIZATIONS_CUH",
        "",
    ]
    output.write_text("\n".join(sections))
    print(output)


if __name__ == "__main__":
    main()
