[pytest]
python_functions = test_* bench*
python_files = test_*.py *_test.py bench_*.py
addopts = --ptjb-output-dir=benchmarks/.results --ptjb-plot -s
testpaths = benchmarks tests
markers =
    multi_gpu: makes only much sense on >= 2 JAX devices (multi-GPU or multi-device)